### PR TITLE
Add memory map comparison 

### PR DESCRIPTION
**Pull request by glpnk**
Add text representation of address space for each data structures + some addresses from 14JKEMS1 EC analysis

### CODE REVIEW

**Comment by BeardOverflow** [comment]
Hi @glpnk 
Thanks for your efforts. The project is growing a lot and we need documentation. Could you reference your mem-map.md from the README.md file? Once you have done, I will merge this

**Comment by glpnk** [comment]
Hi @BeardOverflow 
May be a better way for documentation would be to use a Github Wiki?

**Comment by BeardOverflow** [comment]
Yes. Github Wiki focuses on having short pages and a structured index. Just keep in mind that porting actual README.md file to Github Wiki will require a little effort to adapt its content. At least, on my own, I don't have free time to do it. That's why I suggested you referencing your mem-map.md file into README.md file, for example, with a brief paragraph and a link.

**Comment by glpnk** [comment]
Deprecated, feel free to reuse

**Pull request closed without merging**
