### PR TITLE
add new model "15HKEMS1.104" Modern 15 B7M

### PR DESCRIPTION
**Pull request by glpnk**
issue #89 

[checklist](https://github.com/BeardOverflow/msi-ec/issues/89#issuecomment-1817595636)

### CODE REVIEW

**Comment by teackot** [comment]
This PR is ready, right?

**Comment by glpnk** [comment]
Yeah, seems ready, but now require updating fw number

**Comment by glpnk** [comment]
Do you can resolve conflict, or I need to grant access to my repo?

**Comment by teackot** [comment]
> require updating fw number

Do you mean there's a new version? I can't find any mentions anywhere here

> Do you can resolve conflict

Yes, I'll resove it

**Comment by glpnk** [comment]
I just failed to resolve git conflict

**Comment by teackot** [comment]
Done!

**Pull request merged**
