### PR TITLE
Supported devices list

### PR DESCRIPTION
**Pull request by glpnk**
Part of project documentation

Plans for next PRs:
+ rewrite memory map
+ add RWEverything guide

### CODE REVIEW

**Comment by teackot** [comment]
How about listing the supported features, something like:

| Model                              | Class    | EC name            | Extras                                           | Link                                                                                                                       | Battery thresholds | webcam | ... |
|------------------------------------|----------|--------------------|--------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|:---:|:---:|:---:|
Cool Laptop 15 | Business | 12345678 | | | + | - | ... |

**Comment by glpnk** [comment]
@teackot my last thougths was about using `Discussions` for supported models and other documentation

**Comment by teackot** [comment]
Like using discussions as docs pages? I think this way docs will be lost among questions and firmware requests

We can also use github's wiki feature for this

**Comment by teackot** [comment]
Though the issue with the wiki is that only I and BeardOverflow will be able to edit it. But it would work nice for documenting different features the driver exposes in sysfs. That is, "Usage" section of the current readme.md

**Comment by glpnk** [comment]
This is my second attempt to create "low level" documentation. Also how to implement usable memory map table from #36.

I think mixing code with docs inside same repo is bad, because at least it messing with commit history.

**Comment by glpnk** [comment]
@teackot How do you think about creating repo for wiki repo content? Like you do for issue template

**Comment by teackot** [comment]
> What do you think about creating repo for wiki repo content? Like you do for issue template

I only created issue template repo as a demonstration, it is already merged into this repo. I think creating separate repos for stuff will cause too much fragmentation for a small driver project

**Comment by teackot** [comment]
Oh, I just found out that github wiki can be edited by contributors and is in fact a separate git repo that you can clone and edit locally, it just needs to be enabled in the repo settings

**Comment by teackot** [comment]
Yes

We can make a single contribution guide with a Windows section, a Linux section, and a section about creating a new configuration in the code

**Comment by glpnk** [comment]
@teackot Okay. Not related to this theme but what you think about #48 and similar cases and single `FW` record for two+ different models? Or it pointless in case of possible structural redesign?

**Comment by teackot** [comment]
I will reply in #48

**Comment by teackot** [comment]
@glpnk BeardOverflow gave contributors access to the wiki, see if you can edit it

**Comment by rottenpants466** [comment]
Maybe do something similar to this? 

https://github.com/dmitry-s93/MControlCenter/blob/main/docs/tested_devices.md

**Comment by teackot** [comment]
@rottenpants466 

I think it's a good idea to do a similar table. We already have a list of laptops in README and we can just put them in a separate file with a simple list of features for each machine.

I also think we should put it in the /docs directory of the repo instead of the wiki. Wiki is nice, but it is harder to modify and keep track of.

**Comment by teackot** [comment]
See: #116

**Comment by glpnk** [comment]
Deprecated, feel free to reuse

**Pull request closed without merging**
