### PR TITLE
Documentation: supported devices list

### PR DESCRIPTION
**Pull request by teackot**
I feel like having docs in the base repo is the best way to do this. I think wiki is more difficult to maintain.

You can add/update a device list entry in the same PR when adding a new device or a feature, this way we won't forget to update the docs.

TODO:
- [x] fill the list with devices from README.md
- [x] mention the file in readme (instead of the list right in readme)
- [ ] go through msi-ec.c to see if there are any undocumented models
- [x] add linked issues & PRs
- [ ] sort out the CONF2 and CONF11 thing
- [ ] by glpnk: add WMI version info

### CODE REVIEW

**Comment by glpnk** [comment]
TODO:
+ mention WMI1, WMI2 devices
+ some parameters on some devices is readable, but write does nothing
+ TLDR #98

**Comment by teackot** [comment]
Also, I'm not adding yet:
- super battery (I don't think we fully understand how it works. We use a mask when it might actually be a list of modes)
- cpu&gpu speed&temperature (broken in many configs + there's a driver being merged into the Linux Kernel that implements fan speed interface specifically for MSI)
- backlight modes (not implemented yet)

**Comment by glpnk** [comment]
@teackot What do you think about deprecation of FW ID's and usage of model/board(?) codenames? Codename is `xxxx` part of EC name `xxxxEMSn`/`xxxxIMSn` or BIOS name `ExxxxAMS`/`ExxxxIMS`.

In some cases, one board model is used for few different laptops. Probably they have minor differences

**Comment by teackot** [comment]
We might want do this. There *has* to be a way to do it without hardcoding every possible model.

> one board model is used for few different laptops

Can you give an example? I can't find it in the code. What I can find is 2 different laptops having the same config (which is probs just a coincidense. E.g. 11th config)

What we can *definetly* do rn is drop the minor version (.xxx) (or at least the last 2 digits of it?) as they don't seem to make breaking changes.

**Comment by teackot** [comment]
It would help if we got more data to analyze. Maybe we can anounce the driver on some linux subreddits to get people to give us more dumps

**Comment by glpnk** [comment]
About 
> there's a driver being merged into the Linux Kernel that implements fan speed interface specifically for MSI
https://github.com/jwrdegoede/linux-sunxi/commit/9c0beb6b29e75cacd5fdc63ce6d8502e73e782b8

Look like now it only allows reading of RPM. But I haven't read it in detail.

> What we can definetly do rn is drop the minor version (.xxx) (or at least the last 2 digits of it?) as they don't seem to have breaking changes.

Actually, I think EC name contain more info, so we can drop latest two symbols, which represents version.

`xxxxmMSn.gvv`

+ `x` - model code
+ `m` - EC manufacturer
+ `MS` - probably, Micro Star
+ `n` - board type (?) / differs for model with same model code
+ `g` - board revision / differs between exactly same laptop model
+ `v` - FW version

You can google any model on [MSI support](https://www.msi.com/support) only by using model code.

**Comment by glpnk** [comment]
For start, you can check `14jk`
image
image
So `C7M` use exactly EC as `C5M` `14JKEMS1.104`.

On [same page](https://www.msi.com/Business-Productivity/Modern-14-C7X/support?sub_product=Modern-14-C7M#firmware) mentioned `14JKEMS1.300` with note about incompatibility

**Comment by teackot** [comment]
> g - board revision / differs between exactly same laptop model

You can definitely update the same laptop to a version with a higher `g`. I've seen this update on the MSI Support website of the same laptop, and also mentioned it in some issue, don't remember where. They increased it by 2(?) when they did some breaking USB(?) change

**Comment by teackot** [comment]
> > one board model is used for few different laptops
> 
> Can you give an example? I can't find it in the code. What I can find is 2 different laptops having the same config (which is probs just a coincidense and we shoudn't rely on it. E.g. 11th config)

Oh, I misunderstood you, that's what you're talking about. I have to look into it more thoroughly. And, like I said, we might want to get some more examples (that is, dumps and stuff)

**Comment by glpnk** [comment]
I need some time to find laptops with same board. I'll replace this comment

**Comment by teackot** [comment]
> I need some time to find laptops with same board. I'll replace this comment

Thank you

**Comment by glpnk** [comment]
Actually, we need to switch to WMI if we want to remove the whitelist. Now seems that MSI don't make breaking changes to EC layout (except between WMI1/2)

But how to deal with unsupported features, I don't know. MSI may just use white/blacklists. From https://github.com/lm-sensors/lm-sensors/issues/475#issuecomment-2085062771 we don't found how to get cooler quantity

Also, I want to see MSI Claw users here, but now it seems not popular

**Comment by glpnk** [comment]
Some models have hardware webcam lock, many - only toggle button. But both methods could work on any device

**Comment by glpnk** [comment]
Models with same `model code` but different `n` - `board gen/type` (temp name):

+ [17g1](https://www.msi.com/search/17g1) `17G1EMS1.107` / `17G1EMS2.106` Differs name, CPU, BIOS

**Comment by glpnk** [comment]
I think we shouldn't to mention supported models in two places

**Comment by teackot** [comment]
> I think we shouldn't mention supported models in two places

Sure, I was just going to remove the list in README and add the lile link instead

**Comment by glpnk** [comment]
> It would help if we got more data to analyze. Maybe we can anounce the driver on some linux subreddits to get people to give us more dumps

I'm thinking about Windows program which should continuously dump EC and selected WMI methods. This may be helpful for people who developing similar drivers, OpenHardwareMonitor, OpenRGB. But now I don't promise anything

**Comment by teackot** [comment]
A contribution instruction has to be linked in the same section, but it's out of scope of this PR

**Comment by glpnk** [comment]
We probably need to remake `CPU` and `GPU` sections. Or make `CPU` like `GPU` and add new section for coolers.
Because now some models use wrong addresses, like RPM registers (`0xc9`).

I don't understand what is `bs_fan_speed_address`. It's also named `basic fan speed`, but seems unused on many models. It's definitely not `0xC8-CF`, but may be `0x89`.

Also found few weird models in our issues. `0xA0-BB`: #35 `168AEMS1 Ver4.04, 05/31/2010`, #88 `16K2ED61.1010207201714:10:04`

**Comment by teackot** [comment]
> We probably need to remake `CPU` and `GPU` sections. Or make `CPU` like `GPU` and add new section for coolers.
Because now some models use wrong addresses, like RPM registers (`0xc9`) instead of "realtime" 0-150%.

I too think so

> I don't understand what is bs_fan_speed_address

I think it's supposed to be a constant fan speed setting. Never worked for me: the fan seems to start spinning for a fraction of a second and then stops.

> 16K2ED61

`ED6`, now that's something new. So far it has only been EMS and IMS.

**Comment by glpnk** [comment]
> > 16K2ED61
> 
> `ED6`, now that's something new. So far it has only been EMS and IMS.

You can check on msi site, that now latest EC for this model have EMS name, so probably it can be firmware made by ODM which manufacture hardware for MSI

**Comment by glpnk** [comment]
#issue tags seems not working, we probably need to use permalinks in MD files

**Comment by glpnk** [comment]
| Model                                  | EC version | Issues & PRs | ID | 
|----------------------------------------|------------|--------------|----|
| Modern 15 A11M                         | 1552EMS1   |              |  2 (and 11???) |

Somewhere this was fixed or discussed, I think

**Comment by teackot** [comment]
> `#issue tags` seems not working, we probably need to use permalinks in MD files

Yeah, autolinks don't work in files, the only official way is to put there a long and ugly full link... guess I'll do it

> Somewhere this was fixed or discussed, I think

I remember something like that, I'll get back to it when I fill the `Issues & PRs` column

**Comment by teackot** [comment]
> Somewhere this was fixed or discussed, I think

#48

**Comment by teackot** [comment]
Yay! I added all of them

I think I'll separate the issues and PRs columns

**Comment by glpnk** [comment]
You can use PR instead of # for prs

**Comment by teackot** [comment]
Check [this](https://github.com/teackot/msi-ec/blob/nobr/docs/supported_devices.md) out

**Comment by glpnk** [comment]
Looks good

**Comment by teackot** [comment]
> mention WMI1, WMI2 devices

Can we infer it from hardware using the info from #98 ?

**Comment by glpnk** [comment]
We can group devices by address similarity, or check "class" and CPU of each device. WMI1 devices is Intel up to 10 gen and all AMD, except gaming 7 gen. Also WMI1 devices have separate EC FW on support page

**Comment by glpnk** [comment]
GH issue comment editor is bad... but... I think I accidentally not remove anything.

| Model                                  | EC | WMI |
|----------------------------------------|------------|--------|
| Alpha 15 B5EE / B5EEK                  | 158LEMS1   | 1? |
| Bravo 17 A4DDR / A4DDK                 | 17FKEMS1   | 1? |
| Delta 15 A5EFK                         | 15CKEMS1   | 1? |
| Cyborg 15 A12VF                        | 15K1IMS1   | 2 |
| GP66 Leopard 10UG / 10UE / 10UH        | 1542EMS1   | 1? |
| GP66 Leopard 11UG / 11U\*              | 1543EMS1   | 2 |
| GS66 Stealth 11UE                      | 16V4EMS1   | 2 |
| GF63 Thin 11UC                         | 16R6EMS1   | 2 |
| GF75 Thin 9SC                          | 17F2EMS1   | 1 |
| Katana GF66 11UC / 11UD                | 1582EMS1   | 2 |
| Katana 17 B11UCX                       | 17L2EMS1   | 2 |
| Prestige 14 A10SC                      | 14C1EMS1   | 1 |
| Prestige 15 A11SCX                     | 16S6EMS1   | 2 |
| Prestige 16 Studio A13VE               | 1594EMS1   | 2 |
| Modern 14 C5M                          | 14JKEMS1   | 1 |
| Modern 15 A11M                         | 1552EMS1   | 2 |
| Modern 15 B7M                          | 15HKEMS1   | 1???  |
| Summit E14 Evo A12M                    | 14F1EMS1   | 2 |
| Summit E16 Flip A12UCT / A12MT         | 1592EMS1   | 2 |

**Comment by glpnk** [comment]
Summit and Prestige probably share same board, AMD Modern devices `?5M` and `?7M` seems sharing same board

**Comment by teackot** [comment]
Thanks for help!

> WOW, 20 devices, congrats

That's great! And even more in the issues

**Comment by glpnk** [comment]
@teackot I think you can merge it as is. Other things might be fixed later.

Also, I've checked [`isw`](https://github.com/YoyPa/isw) repo and there are ton of dumps.

**Comment by teackot** [comment]
Sure, I think we'll improve it later with future PRs

**Pull request merged**
