### PR TITLE
Add MSI Katana GF66 11UE and GF66 11UG support

### LINKED ISSUE #38: Support for Katana GF66 11UG
Actually msi_ec prints in dmesg:
`msi_ec: Your firmware version is not supported!`

I prepared some EC dumps and attached files:

```
# sudo od -t x1 /sys/kernel/debug/ec/ec0/io
0000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000040 00 00 00 00 00 00 00 00 0a 05 00 00 00 04 1b 0b
0000060 03 09 00 0d 01 00 50 81 2b 16 28 3c 37 02 e0 00
0000100 00 00 64 00 65 15 00 00 65 15 c5 43 9b 0b 00 00
0000120 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000140 00 00 00 00 00 00 00 00 32 00 37 40 49 4c 52 58
0000160 64 2b 26 2b 30 36 3c 46 55 64 08 03 03 03 03 03
0000200 35 00 37 3d 43 49 4f 54 63 2b 00 2b 30 36 3c 46
0000220 55 64 08 03 03 03 03 02 06 0f 7d 06 0a 78 45 00
0000240 31 35 38 31 45 4d 53 31 2e 31 30 37 30 36 32 38
0000260 32 30 32 32 30 39 3a 30 37 3a 30 38 00 00 00 28
0000300 00 00 01 25 00 00 00 00 00 d3 00 ba 00 00 00 00
0000320 00 00 c1 83 0d 00 05 80 00 01 00 00 00 00 00 00
0000340 e2 00 00 65 15 00 00 00 00 00 00 00 00 00 00 00
0000360 00 00 70 00 00 64 00 00 64 00 00 00 00 00 00 00
0000400
```
---
```
# isw -cp MSI_ADDRESS_DEFAULT

EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 0a 05 00 00 00 04 1b 0b  >................<
000030 03 09 00 0d 01 00 50 81 2b 16 28 3c 37 02 e0 00  >......P.+.(<7...<
000040 00 00 64 00 65 15 00 00 65 15 c2 43 b4 0b 00 00  >..d.e...e..C....<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 35 00 37 40 49 4c 52 58  >........5.7@ILRX<
000070 64 2b 26 2b 30 36 3c 46 55 64 08 03 03 03 03 03  >d+&+06<FUd......<
000080 38 00 37 3d 43 49 4f 54 63 2b 00 2b 30 36 3c 46  >8.7=CIOTc+.+06<F<
000090 55 64 08 03 03 03 03 02 06 0f 7d 06 0a 78 49 00  >Ud........}..xI.<
0000a0 31 35 38 31 45 4d 53 31 2e 31 30 37 30 36 32 38  >1581EMS1.1070628<
0000b0 32 30 32 32 30 39 3a 30 37 3a 30 38 00 00 00 28  >202209:07:08...(<
0000c0 00 00 01 25 00 00 00 00 00 a2 00 b5 00 00 00 00  >...%............<
0000d0 00 00 c1 83 0d 00 05 80 00 01 00 00 00 00 00 00  >................<
0000e0 e2 00 00 65 15 00 00 00 00 00 00 00 00 00 00 00  >...e............<
0000f0 00 00 70 00 00 64 00 00 64 00 00 00 00 00 00 00  >..p..d..d.......<
000100

Profile dump 
Value       set @ address        Fan mode
0x0(0)      0xf4(byte244)        Unknown

-----------CPU-----------        -----------GPU-----------
Value       set @ address        Value       set @ address
0x37(55°C)  0x6a(byte106)        0x37(55°C)  0x82(byte130)
0x40(64°C)  0x6b(byte107)        0x3d(61°C)  0x83(byte131)
0x49(73°C)  0x6c(byte108)        0x43(67°C)  0x84(byte132)
0x4c(76°C)  0x6d(byte109)        0x49(73°C)  0x85(byte133)
0x52(82°C)  0x6e(byte110)        0x4f(79°C)  0x86(byte134)
0x58(88°C)  0x6f(byte111)        0x54(84°C)  0x87(byte135)

0x26(38%)   0x72(byte114)        0x0(0%)     0x8a(byte138)
0x2b(43%)   0x73(byte115)        0x2b(43%)   0x8b(byte139)
0x30(48%)   0x74(byte116)        0x30(48%)   0x8c(byte140)
0x36(54%)   0x75(byte117)        0x36(54%)   0x8d(byte141)
0x3c(60%)   0x76(byte118)        0x3c(60%)   0x8e(byte142)
0x46(70%)   0x77(byte119)        0x46(70%)   0x8f(byte143)
0x55(85%)   0x78(byte120)        0x55(85%)   0x90(byte144)
```
[ec.txt](https://github.com/BeardOverflow/msi-ec/files/11293305/ec.txt)

`# cat /sys/kernel/debug/ec/ec0/io > ec0.bin`
[ec0.bin.txt](https://github.com/BeardOverflow/msi-ec/files/11293308/ec0.bin.txt)
`# cat /sys/kernel/debug/ec/ec0/gpe > gpe0.bin`
[gpe0.bin.txt](https://github.com/BeardOverflow/msi-ec/files/11293309/gpe0.bin.txt)

### PR DESCRIPTION
**Pull request by TGODiamond**
Fn <-> Windows works, but the files report the opposite.

Real-time fan monitoring is not accurate: GPU rt fan file can report over 100%, and CPU rt fan file is very weird. It is like address `0xc9` isn't even linearly representing the CPU fan speed.

Everything else works.

### EC Dump
```
     | _0 _1 _2 _3 _4 _5 _6 _7 _8 _9 _a _b _c _d _e _f
-----+------------------------------------------------
0x0_ | 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x1_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x2_ | 00 00 00 00 00 00 00 00 0a 05 00 00 02 04 0b 0b
0x3_ | 03 01 00 0d 00 00 50 81 d2 11 88 2c c8 01 c0 00
0x4_ | f8 11 5e 00 d1 0f 00 00 c5 0e 28 31 f6 0b fa 32
0x5_ | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x6_ | 00 00 00 00 00 00 00 00 36 00 37 40 49 4c 52 58
0x7_ | 64 2b 26 2b 30 36 3c 46 55 64 08 03 03 03 03 03
0x8_ | 32 00 37 3d 43 49 4f 54 63 00 00 2b 30 36 3c 46
0x9_ | 55 64 08 03 03 03 03 02 06 0f 7d 06 0a 78 45 00
0xa_ | 31 35 38 31 45 4d 53 31 2e 31 30 37 30 36 32 38
0xb_ | 32 30 32 32 30 39 3a 30 37 3a 30 38 00 00 00 28
0xc_ | 00 00 01 00 00 00 00 00 00 d3 00 00 00 00 00 00
0xd_ | 00 00 c4 81 0d 00 05 d0 00 01 00 00 00 00 00 00
0xe_ | e2 00 00 d1 0f 00 00 40 00 00 00 00 00 d1 00 00
0xf_ | 40 00 70 00 00 64 00 00 64 00 00 00 00 00 00 00
```

### CODE REVIEW

**Comment by glpnk** [comment]
Nice work!

Please mention #38 in docs.

> `.rt_fan_speed_address = 0xc9,`

Actually, original meaning of this value seems to be %RPM of the CPU cooler, but it's badly documented and misunderstood by other contributors. It also has limits, for some reason. Probably, all coolers might use %RPM in range of 0-150% if other not stated in MSI app for custom fan curve. And the right address for your device should be `0x71`. According to fan curve from dump, maximal %RPM should be 100%, but I think in `cooler boost` it might be set to 150%, which you need to check.

`0xC8-CF` addresses are n/RPM values, and your kernel might have a module which LM-sensors use to get RPM

**Comment by glpnk** [comment]
Yeah, on silent is some different fan curve is used. In LM sensors driver realtime RPM calculated like this
```
RPMcpu = 48000 / ({0xc8} << 8 + {0xc9})
```
GPU is similar, but with next pair. Also, seems like exist laptops with 3 and 4 coolers

**Comment by TGODiamond** [comment]
Also, turning on cooler boost doesn't directly change `0x71` and `0x89`.

**Comment by TGODiamond** [comment]
It only changes since the temperature changes, thus changing the fan curve's wanted fan speed percent.

**Comment by glpnk** [comment]
I tried to write into CPU %rpm address, it starts cooler, then stops it

**Comment by TGODiamond** [comment]
Added GF66 11UG to docs and comments

**Comment by teackot** [comment]
Is this one also ready to be merged?

**Comment by TGODiamond** [comment]
Only rt fan speed monitoring is not working properly, otherwise it's ready to be merged.

**Comment by glpnk** [comment]
CPU realtime speed `.rt_fan_speed_address` is `0x71`

**Comment by teackot** [comment]
From what I understood from this discussion, 0x71 is the speed preferred by the auto mode. So what is 0xc9?

**Comment by TGODiamond** [comment]
Does RT fan speed have anything to do with the custom fan curves? Because if not, then it's `0xc9` with `0xc8` used as an overflow. Also, advanced mode should be the only mode where `0x71` is actually used.

**Comment by glpnk** [comment]
image

`0xC8-CF` values are RPM related values. 2 bytes per cooler

```
RPMcpu = 48000 / ({0xc8} << 8 + {0xc9})
```

**Comment by glpnk** [comment]
This values now used by `lm-sensors` module which used to show coolers RPM

**Comment by TGODiamond** [comment]
Also, I found out that it should be 480000, not 48000.

Found it out from here:
[https://github.com/torvalds/linux/blob/master/drivers/platform/x86/msi-wmi-platform.c#L188C10-L188C16](url)

Tested that, and works much better.

**Comment by glpnk** [comment]
> Also, I found out that it should be 480000, not 48000.

I just remembered it incorrectly

Thanks for the link, check does your kernel have this module with `sensors` command, after installing `lm-sensors` package

**Comment by TGODiamond** [comment]
Yes, it outputs this:

```
❯ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +39.0°C  

BAT1-acpi-0
Adapter: ACPI interface
in0:          11.98 V  
curr1:         0.00 A  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +56.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +49.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +52.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +52.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +51.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +51.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +46.0°C  (high = +100.0°C, crit = +100.0°C)

nvme-pci-0200
Adapter: PCI adapter
Composite:    +30.9°C  (low  = -273.1°C, high = +80.8°C)
                       (crit = +84.8°C)
Sensor 1:     +30.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +57.0°C  

```

**Comment by glpnk** [comment]
Your kernel probably don't have this module

**Comment by TGODiamond** [comment]
Oh I see, I'm only running kernel 6.9.3

**Comment by teackot** [comment]
My fan uses 0xcd, with 0xc9 having no effect

So, considering the overflow thing, can c8:c9, ca:cb, cc:cd and ce:cf correspond to different fan "slots"?

**Comment by glpnk** [comment]
Yes, also, `c8:c9` and `ca-cb` used in MControlCenter as RPM for CPU and GPU https://github.com/dmitry-s93/MControlCenter/blob/main/src/operate.cpp#L164-L176

**Comment by TGODiamond** [comment]
For me, it's c8:c9 for the cpu fan and ca:cb for the gpu fan. So yea, that must be the case.

**Comment by glpnk** [comment]
Actually, WMI-ACPI (ver 2), which your device use, maps few address groups, map based on DSDT

Fan
image

Temperature
image

Thermal (IDK WTF is this and how works)
image

**Comment by teackot** [comment]
We've got the addresses right, so this PR is ready.

The fan speed formulas need to be reworked and we need to implement the auto mode (0x71 can be used to display the current temp threshold), but that's for a different PR. Merging this one

**Comment by glpnk** [comment]
@teackot as you mentioned in #98, you have Intel gen 10 device. Your and my device use older WMI-ACPI layout, but it have fan curve + cooler RPM registers on same addresses, but use different WMI name. 

In generation 1 WMI layout RPM section called `AP`
image

For some reason, my device sometimes stores garbage in random registers + randomize real cooler position

**Comment by teackot** [comment]
@glpnk how many coolers do you have?

> randomize real cooler position

Like the cooler address changes? I haven't noticed this on my device

**Comment by glpnk** [comment]
Do we need to recreate functions which other module handles now?

IDK how originally this method worked, because some devices mention `RPM=480000/X` address, other `%RPM`

> how many coolers do you actually have?

1 cooler. On screenshot was old dump, on newer exist few garbage values + real cooler is 3rd:
image psd

**Comment by TGODiamond** [comment]
Remember to mark #38 as completed.

**Comment by teackot** [comment]
> Do we need to recreate functions which other module handles now?

Right, we don't, only the curve. Should we just remove the fan_speed_show functions?

> 1 cooler. On previous screenshot was old dump. On newer, I've highlighted garbage values + real cooler is 3rd

My EC also spits garbage at 0xc9. Maybe the EC tries to read the values on all the "slots" and the garbage ones are just not wired to actual sensors, so it reads random noise?

**Comment by glpnk** [comment]
> Should we just remove the fan_speed_show functions?

I think we don't need to remove it completely, just fix realtime addresses for all devices and remove normalization https://github.com/BeardOverflow/msi-ec/blob/02f08cf67740aed5b80aff642750b06396fb7001/msi-ec.c#L2497-L2499

Plus we need to figure out what is basic fan speed, and why some devices refers GPU %RPM value for it

> Maybe the EC tries to read the values on all the "slots" and the garbage ones are just not wired to actual sensors, so it reads random noise?

I think this values are timers and they returning value after cooler sends pulse. So they might catch some noise

**Comment by AntyElo** [comment]
msi-ec failing to load with `msi_ec: Your firmware version is not supported!` on my Katana GF66 11UE (1581EMS1.105) lol

**Comment by glpnk** [comment]
Wait for new release some time

**Pull request merged**
