### PR TITLE
Titan 18 HX A14V [1822EMS1]

### PR DESCRIPTION
**Pull request by glpnk**
#105

### CODE REVIEW

**Comment by sempervictus** [comment]
Probably a good idea to introduce a "MAYBRICK" danger tag or something like that to help bots which build PRs avoid by tag.

**Comment by glpnk** [comment]
I think someone tested this version, but I need to recheck something. Basically, many laptops have similar configs, but some features are unavailable

**Comment by sempervictus** [comment]
@glpnk - anything i can do to help this PR along?

**Comment by glpnk** [comment]
Looks like ready, but require checking ability to set keyboard backlight, because some SteelSeries keyboard don't use EC, but MSI program writing dummy values

Thanks for waiting, @makintos @nalim @sempervictus 
Thanks to @makintos for research

**Comment by sempervictus** [comment]
Seems to work for battery threshold anyway:
```
# /etc/systemd/system/battery-charge-save-threshold.service
[Unit]
Description=Set the battery charge threshold to max lifetime
After=multi-user.target
StartLimitBurst=0
#Conflicts=battery-charge-full-threshold,battery-charge-balanced-threshold

[Service]
Type=oneshot
Restart=on-failure
ExecStart=/bin/bash -c 'echo min > /sys/devices/platform/msi-ec/battery_mode && echo "Battery charge threshold $(cat /sys/devices/platform/msi-ec/battery_mode)"'

[Install]
WantedBy=multi-user.target
```
Hasn't blown up my laptop or thrown any errors in compilation using GCC14.1 with pretty much every Grsec/PaX plugin enabled.

**Comment by glpnk** [comment]
@sempervictus 
Have you tested ability to change keyboard brightness from linux?

**Comment by sempervictus** [comment]
Keyboard brightness works, touchpad `fn` key does not. Touchpad is actually kind of weird - using `libinput` with X, i am finding that the "physical click" pressure changes becoming _very_ sensitive to accidental contact when typing and that the "disable touchpad while typing" function in Cinnamon's touchpad settings does not work. Otherwise, super-battery mode, charge adjustment thresholds, keyboard brightness, microphone, fan speed, and volume all work as expected

**Comment by glpnk** [comment]
@sempervictus 

> touchpad fn key does not

What? How this look like? And how should work?

How actually super battery works? Is it reduces CPU/GPU speed? Because I'm not have it.

image
Is this really keyboard sized touchpad?

**Comment by sempervictus** [comment]
Touchpad is about size of space bar integral to the surface. The whole area has mechanical click and it appears to be pressure adjustable but that adjustment sort of swims randomly.
Superbat slows all the chips, kills discrete GPU AFAIK (no idea, can't use nvidia drivers with any form of CFI as they perform function hijacking), and limits fans accordingly. Seems to get about an hour of added life

**Comment by glpnk** [comment]
Thanks, you probably need to ask community of your touchpad manufacturer, if it is really possible

**Comment by teackot** [comment]
TODO: docs

**Comment by teackot** [comment]
@glpnk we still need to implement those unusual kbd backlight intensity values, right?

**Comment by glpnk** [comment]
@teackot we just ignore keyboard brightness for RGB and per key RGB keyboards, value in EC just cycles and MSI app receive key press events

**Pull request merged**
