### PR TITLE
Remove BIOS versions from allowed firmware list

### PR DESCRIPTION
**Pull request by rottenpants466**
Added a new firmware version: E1592IMS.10F

### CODE REVIEW

**Comment by teackot** [comment]
Does this PR make the driver work on new firmware? It seems that the versions that start with E are BIOS FW versions, not EC FW

**Comment by rottenpants466** [comment]
> 

It works with this PR prior to kernel 6.4.

This is the change log from msi:

New BIOS     : 	E1592IMS.10F 
ROM CheckSum :  0x1B27 
Release Date :  2024/7/14

;--------------------------- Description ------------------------------------;

1.Enhanced security protection against unauthorized BIOS updates.

**Comment by teackot** [comment]
Okay then, looks good to me

**Comment by teackot** [comment]
Okay, so now that we know that `E1592IMS.10C/D/F` is actually BIOS and not EC, can you please remove those three from the allowed fw array? You can even do it in this PR, just rename it after

**Comment by teackot** [comment]
Yep, everything's correct, thank you too!

**Pull request merged**
