### PR TITLE
Support for MSI Alpha 17 B5EEK

### PR DESCRIPTION
**Pull request by mutchiko**

### CODE REVIEW

**Comment by teackot** [comment]
Thank you! My PR has been hanging there for more than a year :)

Fixing conflicts, adding docs and merging

**Comment by TGODiamond** [comment]
Any reason why `.invert` wasnt't added in `.fn_win_swap`?

**Comment by TGODiamond** [comment]
Nevermind, just GitHub not showing the same as the actual merged change under "files changed"....

**Comment by mutchiko** [comment]
thanks for the merge, .invert should be true for this laptop.

**Comment by teackot** [comment]
> Nevermind, just GitHub not showing the same as the actual merged change under "files changed"....

That's because it's my commit and not exactly a part of this PR

> .invert should be true for this laptop.

Oh, I missed that, sure

**Pull request merged**
