### PR TITLE
msi-ec : add support gp66-11ug

### PR DESCRIPTION
**Pull request by perseusdg**
This pull request adds support for msi gp66-11ug, I am guessing that this commit should work with other gp66-11u variants and gp76-11u variants.

### CODE REVIEW

**Comment by teackot** [comment]
Hi! Have you tested all of the features? Also can you please attach an EC dump (`/sys/devices/platform/msi-ec/debug/ec_dump` with debug mode on) here, so we can use it as a reference in the future

**Comment by perseusdg** [comment]
I did test out most of them , the only thing i couldn't verify properly was the gpu and cpu fan speed..I will attach the ec dump in a couple of days

**Comment by teackot** [comment]
I think that since you've tested it out, I can merge it. Some dumps woud still be appreciated though

Thank you!

**Comment by teackot** [comment]
Actually, we have a dump in #95

**Comment by NamitBhutani** [comment]
Hi, I have a MSI GP76 11UG, and advanced fan speed control doesn't seem to work on nixos. Cooler boost works and disabling the webcam works tho.

**Pull request merged**
